export const GET_GITHUB_REPOS_DONE = 'GET_GITHUB_REPOS_DONE';
export const GET_GITHUB_REPOS_PENDING = 'GET_GITHUB_REPOS_PENDING';
export const GET_MEDIUM_POSTS_DONE = 'GET_MEDIUM_POSTS_DONE';
export const GET_MEDIUM_POSTS_PENDING = 'GET_MEDIUM_POSTS_PENDING';
export const GET_TWITTER_TWEETS_DONE = 'GET_TWITTER_TWEETS_DONE';
export const GET_TWITTER_TWEETS_PENDING = 'GET_TWITTER_TWEETS_PENDING';
